spring:
  datasource:
    url: jdbc:mysql://magilhub-intern.cb60w4qgw0y3.ap-south-1.rds.amazonaws.com:3306/A2B_Dynamic_Styling
    username: Intern
    password: Internmagil
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true